### ISSUE TITLE
yysy，这是个好东西

### ISSUE THREAD

**Issue by lycohana** [MonianHello/tianyupadkiller#1]
我是翻转班的学生
我也在用这个系统

这年头，它确实改变了很多，但是bug特别多
现在发这条消息是用天喻的平板发的
我破解他没有用到电脑等
纯手工（

希望这个程序能有更好的发挥

最后，谢谢你，你是GitHub第一个整这个的人（

**Comment by MonianHello** [comment]
我就好奇你怎么找到这的
这东西没能撑过我们平板更新，更新之后电脑压根不识别设备

纯手工破解怎么弄的，听说OTG转接头+U盘可以，但是没试过

（再骂一句 天喻垃圾

**Comment by lycohana** [comment]
看了看你们学校的智慧云教学平台
确实是一个板子里刻出来的
最近我和我同学报了很多bug
结果照样可以破

卡出学生桌面进程，把它强行停止
重新安装WPS，wps就可以连网了
会面的就不必多说了

天喻的技术头发都长满了（
